stages:
  - build
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > key.pem
  - chmod 600 key.pem
  - ssh-add key.pem
  - mkdir -p ~/.ssh
  - ssh-keyscan -H 65.2.149.240 >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - ./mvnw clean install -DskipTests

deploy:
  stage: deploy
  script:
    - ssh ubuntu@65.2.149.240 "
      cd /home/ubuntu/app || mkdir -p /home/ubuntu/app && cd /home/ubuntu/app &&
      git clone https://gitlab.com/vipul-group2/shopping.git . || git pull &&
      ./mvnw clean install &&
      pkill -f java || true &&
      nohup java -jar target/*.jar > app.log 2>&1 &
      "
  only:
    - main